/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import ADMIN.ADD;
import static java.lang.Character.isDigit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import user1.FACT;



/**
 *
 * @author RAHUL
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Statement stat;
    Connection con;
    
    public login() {
        initComponents();
        try
        {
            
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
        JOptionPane.showMessageDialog(null,"connected");
    }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not Connected");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        user_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        signup.setText("SIGNUP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        user_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                user_nameKeyTyped(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 53, 128, -1));

        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, -1, -1));

        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DON'T HAVE AN ACCOUNT?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 203, 160, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 103, 128, -1));

        jLabel4.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel4.setText("qmania");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/PicsArt_07-13-05.16.23.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String User_name=user_name.getText();
        String Password=password.getText();
        String Pass="";
        String User="";
        String Type="";
        
        try
        {
            
            PreparedStatement pr=con.prepareStatement("select * from users");
            ResultSet rs=pr.executeQuery();
            while(rs.next())
            {
             if
                     (User_name.equals(rs.getString(2))) 
             {
                 
                 break;
             }
        }
                    User=rs.getString(2);
                 Pass=rs.getString(4);
                 Type=rs.getString(5);
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(null,"error"+e);
        }
        
        if(Type.equals("admin"))
        {
            if(Password.equals(Pass))
            {
                ADD obj1=new ADD();
                obj1.setVisible(true);
                dispose();
            }
            else
            JOptionPane.showMessageDialog(null,"INCORRECT ID OR PASSWORD");
        }
        else if(Type.equals("student"))
        {
            if(Password.equals(Pass))
            {
                try {
                    FACT obj2=new FACT(User);
                    obj2.setVisible(true);
                    dispose();
                } 
                catch (Exception e) {
                   
                }
            }
            else
            JOptionPane.showMessageDialog(null,"INCORRECT ID OR PASSWORD");
  
        }
        else
        {
            JOptionPane.showMessageDialog(null,"INVALID USERNAME,DOES NOT HAVE ACCOUNT?");
        }
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        SIGNUP obj=new SIGNUP();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_signupActionPerformed

    private void user_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_nameKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(c==' ' && c!='\b'){
            evt.consume();
        }
    }//GEN-LAST:event_user_nameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
