/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RAHUL
 */
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    Statement stat;
    Connection con;
    char c=' ';
  
    public SIGNUP() {
        initComponents();
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
           JOptionPane.showMessageDialog(null,"connected");
           
        }
        catch(Exception e)

        {
            JOptionPane.showMessageDialog(null,"connected");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 32, 129, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 70, 129, -1));

        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 108, 28, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 146, 129, -1));
        getContentPane().add(confpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 184, 129, -1));

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        jLabel3.setText("AGE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));

        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, -1));

        jLabel5.setText("CONFIM PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, -1));

        signup.setText("SIGNUP");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 235, -1, -1));

        jLabel6.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel6.setText("qMANiA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 5, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/PicsArt_07-13-05.16.23.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        // TODO add your handling code here:

            String Name=name.getText();
            String Username=username.getText();
            String Age=age.getText();
            String Password=password.getText();
            String ConfPassword=confpassword.getText();
            String Type="student";
            String User_name="";
            String first="0";
            try
            {
                PreparedStatement pr=con.prepareStatement("select * from users");
                ResultSet rs=pr.executeQuery();
            while(rs.next())
            {
            if(Username.equals(rs.getString(2)))
            {
                JOptionPane.showMessageDialog(null,"Username Already Taken");
                User_name=rs.getString(2);
                break;
             }
            }
            }
            catch(Exception e)
            {
                
            }
            if(!Username.equals(User_name))
            {
             
                if(Password.equals(ConfPassword))
                {
                    try
                    {
                        stat=con.createStatement();
                        stat.execute("insert into users values('"+Name+"','"+Username+"','"+Age+"','"+Password+"','"+Type+"')");
                        JOptionPane.showMessageDialog(null,"inserted");
                         login obj=new login();
                          obj.setVisible(true);
        dispose();
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"not Inserted"+e);
                    }
                    try
                    {
                        stat.execute("insert into cricket_data values('"+Username+"','"+first+"','"+first+"','"+first+"','"+first+"')");
                        stat.addBatch("insert into gk_data values('"+Username+"','"+first+"','"+first+"','"+first+"','"+first+"')");
                        stat.execute("insert into science_data values('"+Username+"','"+first+"','"+first+"','"+first+"','"+first+"')");
                        stat.execute("insert into random_data values('"+Username+"','"+first+"','"+first+"','"+first+"','"+first+"')");
                        stat.execute("insert into user_data values('"+Username+"','"+first+"','"+first+"','"+first+"',1)");
                        stat.execute("insert into rank values('"+Username+"','"+first+"')");
                    }
                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null,"data not inserted"+e);
                    }
                }
                
                else
                {
                    JOptionPane.showMessageDialog(null,"CONFIRM PASSWORD");
                }
        }
    }//GEN-LAST:event_signupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        login obj=new login();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        // TODO add your handling code here:
        
     
       
    }//GEN-LAST:event_ageKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_nameKeyPressed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
  
        // TODO add your handling code here:  
        c=evt.getKeyChar();
        if(isDigit(c) && c!='\b'){
            evt.consume();
        }
    }//GEN-LAST:event_nameKeyTyped

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        // TODO add your handling code here:
          c=evt.getKeyChar();
        if(!isDigit(c) && c!='\b'){
            evt.consume();
            
        }
    }//GEN-LAST:event_ageKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JPasswordField confpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
