package user1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAHUL
 */
public class FACT extends javax.swing.JFrame {

    /**
     * Creates new form USER_SCIENCE
     */
    Connection con;
    Statement stat;
    String Fact="";
    int Num=1;
    
    String Level="";
    String Rank="";
    String Points="";
    String User="";
    int POINTS=0;
    int RANK=0;
    int LEVEL=0;
    
    
    public FACT(String User) throws ClassNotFoundException, SQLException {
        initComponents();
        this.User=User;
        int ranks=0;
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
       
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not Connected");
        }
        try{
            
            stat=con.createStatement();
        PreparedStatement pr1=con.prepareStatement("select * from user_data");
        PreparedStatement PR2=con.prepareStatement("select * from rank  ORDER by score desc");
        ResultSet RS2=PR2.executeQuery();
        ResultSet rs1=pr1.executeQuery();
        while(rs1.next())
        {
            if(User.equals(rs1.getString(1)))
               
                {
              
            
            
            User=rs1.getString(1);
            Num=Integer.parseInt(rs1.getString(5));
            
            
            
            break;
        }
                }
        while(RS2.next())
        {
            ranks++;
            String Ranks=Integer.toString(ranks);
            if(RS2.getString(1).equals(User))
            {
                Points=RS2.getString(2);
                points.setText(Points);
                rank.setText(Ranks);
                
                break;
            }
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not");
            
        }
        try
        {
            PreparedStatement pr2=con.prepareStatement("select * from fact");
             ResultSet rs2=pr2.executeQuery();
            Num++;
            while(rs2.next())
            {
                if(Num==Integer.parseInt(rs2.getString(1)))
                {
                    Num++;
                    break;
                    
                }
              
             
            }
            POINTS=Integer.parseInt(Points);
            RANK =Integer.parseInt(Rank);
            LEVEL=Integer.parseInt(Level);
            Fact=rs2.getString(2);
            fact.setText(Fact);
            
            stat.executeUpdate("update user_data  set username='"+User+"', Point='"+POINTS+"',rank='"+RANK+"',level='"+LEVEL+"',Fact='"+Num+"' where username='"+User+"'");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not inseeted"+e);
            Num=1;
            stat.executeUpdate("update user_data  set username='"+User+"', Point='"+POINTS+"',rank='"+RANK+"',level='"+LEVEL+"',Fact='"+Num+"' where username='"+User+"'");
        }
    }

   



   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        rank = new javax.swing.JTextField();
        fact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        next_fact = new javax.swing.JButton();
        start_test = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        points = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("RANK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        rank.setEditable(false);
        rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankActionPerformed(evt);
            }
        });
        getContentPane().add(rank, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 50, 50, 20));

        fact.setEditable(false);
        fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factActionPerformed(evt);
            }
        });
        getContentPane().add(fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 133, 278, 73));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("DO YOU KNOW?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 100, -1, -1));

        next_fact.setText("NEXT FACT");
        next_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_factActionPerformed(evt);
            }
        });
        getContentPane().add(next_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 217, -1, -1));

        start_test.setText("START TEST");
        start_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_testActionPerformed(evt);
            }
        });
        getContentPane().add(start_test, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("TOTAL POINTS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        points.setEditable(false);
        points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointsActionPerformed(evt);
            }
        });
        getContentPane().add(points, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, -1));

        jLabel9.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel9.setText("qMAINA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/PicsArt_07-13-05.16.23.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 370, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_testActionPerformed
        // TODO add your handling code here:
        USER obj=new USER(User);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_start_testActionPerformed

    private void next_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_factActionPerformed
        // TODO add your handling code here:
        try
        {
            
         PreparedStatement pr2=con.prepareStatement("select * from fact");
             ResultSet rs2=pr2.executeQuery();
             while(rs2.next())
             {
                 if(Num==Integer.parseInt(rs2.getString(1)))
                   Fact=rs2.getString(2);
             }
       
        fact.setText(Fact);
        Num++;
        
        stat.executeUpdate("update user_data  set username='"+User+"', Point='"+POINTS+"',rank='"+RANK+"',level='"+LEVEL+"',Fact='"+Num+"' where username='"+User+"'");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not pressed"+e);
        }
        
        
    }//GEN-LAST:event_next_factActionPerformed

    private void factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factActionPerformed

    private void rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankActionPerformed

    private void pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FACT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String User="";
                try {
                    new FACT(User).setVisible(true);
                } 
                catch (Exception e) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fact;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JButton next_fact;
    private javax.swing.JTextField points;
    private javax.swing.JTextField rank;
    private javax.swing.JButton start_test;
    // End of variables declaration//GEN-END:variables
}
