package user1;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAHUL
 */
public class USER extends javax.swing.JFrame {

    /**
     * Creates new form USER
     */
    String User="";
    public USER(String User) {
        this.User=User;
        initComponents();
        JOptionPane.showMessageDialog(null,User);
    }

    public USER() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        science = new javax.swing.JRadioButton();
        gk = new javax.swing.JRadioButton();
        cricket = new javax.swing.JRadioButton();
        random = new javax.swing.JRadioButton();
        ok = new javax.swing.JButton();
        top = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("TOPIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 70, 40, -1));

        buttonGroup1.add(science);
        science.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        science.setText("SCIENCE");
        getContentPane().add(science, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 112, -1, -1));

        buttonGroup1.add(gk);
        gk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gk.setText("GENERAL KNOWLEDGE");
        getContentPane().add(gk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 112, -1, -1));

        buttonGroup1.add(cricket);
        cricket.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cricket.setText("CRICKET");
        getContentPane().add(cricket, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 153, -1, -1));

        buttonGroup1.add(random);
        random.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        random.setText("RANDOM");
        getContentPane().add(random, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 153, -1, -1));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 216, -1, -1));

        top.setText("TOP 10 ");
        top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topActionPerformed(evt);
            }
        });
        getContentPane().add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel9.setText("qMAINA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 0, -1, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMIN/PicsArt_07-13-05.16.23.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        
        
        if(science.isSelected())
        {
            TEST_SCIENCE obj=new TEST_SCIENCE(User);
         obj.setVisible(true);
         dispose();
        }
        else if(gk.isSelected())
        {
           TEST_GK obj1=new TEST_GK(User);
         obj1.setVisible(true);
         dispose();
        }
        else if(cricket.isSelected())
        {
           TEST_CRICKET obj2=new TEST_CRICKET(User);
           obj2.setVisible(true);
           dispose(); 
        }
        else if(random.isSelected())
        {
            TEST_RANDOM obj3=new TEST_RANDOM(User);
            obj3.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select any option");
        }
    }//GEN-LAST:event_okActionPerformed

    private void topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topActionPerformed
        // TODO add your handling code here:
        TOP obj=new TOP();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_topActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
       FACT obj1=new FACT(User);
       obj1.setVisible(true);
       dispose();}
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String User="";
                new USER(User).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cricket;
    private javax.swing.JRadioButton gk;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton random;
    private javax.swing.JRadioButton science;
    private javax.swing.JButton top;
    // End of variables declaration//GEN-END:variables
}
