/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RAHUL
 */
public class ADD extends javax.swing.JFrame {

    /**
     * Creates new form ADD
     */
    Connection con;
    Statement stat;
    public ADD() {
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
        JOptionPane.showMessageDialog(null,"connected");
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,"connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        SCIENCE = new javax.swing.JRadioButton();
        GK = new javax.swing.JRadioButton();
        CRICKET = new javax.swing.JRadioButton();
        RANDOM = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        FACTS = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("BACK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(SCIENCE);
        SCIENCE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SCIENCE.setText("SCIENCE");
        getContentPane().add(SCIENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 73, -1, -1));

        buttonGroup1.add(GK);
        GK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        GK.setText("GENERAL KNOWLEDGE");
        getContentPane().add(GK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        buttonGroup1.add(CRICKET);
        CRICKET.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CRICKET.setText("CRICKET");
        getContentPane().add(CRICKET, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, -1, -1));

        buttonGroup1.add(RANDOM);
        RANDOM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RANDOM.setText("RANDOM");
        getContentPane().add(RANDOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        buttonGroup1.add(FACTS);
        FACTS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FACTS.setText("FACTS");
        getContentPane().add(FACTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel1.setText("qMAINA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jButton2.setText("BACK");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMIN/PicsArt_07-13-05.16.23.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        String next=" ";
        
       if(SCIENCE.isSelected())
       {
       next="SCIENCE";
       
       }
       else if(GK.isSelected())
       {
           next="GK";
       }
       else if(RANDOM.isSelected())
       {
           next="RANDOM";
       }
       else if(FACTS.isSelected())
       {
           FACT_ADMIN obj2=new FACT_ADMIN();
           obj2.setVisible(true);
           dispose();
       }
       else if(CRICKET.isSelected())
       {
           next="CRICKET";
       }
       else
       {
           JOptionPane.showMessageDialog(null,"SELECT OPTION");
       }
       if(next!=" ")
       {
           Questions obj=new Questions(next);
           obj.setVisible(true);
           dispose();
       }
       
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CRICKET;
    private javax.swing.JRadioButton FACTS;
    private javax.swing.JRadioButton GK;
    private javax.swing.JRadioButton RANDOM;
    private javax.swing.JRadioButton SCIENCE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
