/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ADMIN;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author RAHUL
 */
public class Questions extends javax.swing.JFrame {

    /**
     * Creates new form Questions
     */
    Connection con;
    Statement stat;
    String Next;
    int Num=1;
    
    public Questions(String Next) {
        
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/quiz","root","");
        JOptionPane.showConfirmDialog(null,Next);
        this.Next=Next;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not Connected"+e);
        }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        optiona = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        optionb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        optionc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        optiond = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        upload = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("QUESTION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 33, 223, 71));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("A");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(optiona, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 137, 125, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("B");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 140, -1, -1));
        getContentPane().add(optionb, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 137, 125, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("C");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, -1));
        getContentPane().add(optionc, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 175, 125, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("D");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 178, -1, -1));
        getContentPane().add(optiond, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 175, 125, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CORRECT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        buttonGroup1.add(A);
        A.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A.setText("A");
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 206, -1, -1));

        buttonGroup1.add(B);
        B.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B.setText("B");
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 206, -1, -1));

        buttonGroup1.add(C);
        C.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        C.setText("C");
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 206, -1, -1));

        buttonGroup1.add(D);
        D.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        D.setText("D");
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 206, -1, -1));

        upload.setText("UPLOAD");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 206, -1, -1));

        jLabel9.setFont(new java.awt.Font("Team MT", 1, 18)); // NOI18N
        jLabel9.setText("qMANiA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 0, -1, -1));

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ADMIN/PicsArt_07-13-05.16.23.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        
        String Question=question.getText();
        String OptionA=optiona.getText();
        String OptionB=optionb.getText();
        String OptionC=optionc.getText();
        String OptionD=optiond.getText();
        char Correct=' ';
       
        
        if(A.isSelected())
        {
            Correct='A';
            
        }
        else if(B.isSelected())
                {
                 Correct='B';
                 
                }
        else if(C.isSelected())
                {
                    Correct='C';
                }
        else if(D.isSelected())
                {
                    Correct='D';
                }
        else
        {
                JOptionPane.showMessageDialog(null,"select correct Answer");
         }
        if(Correct!=' ')
        {
            if(Next.equals("GK"))
            {
                try
        {
            PreparedStatement pr=con.prepareStatement("select * from gk_questions");
            ResultSet rs=pr.executeQuery();
            
            rs.last();
            String num=rs.getString(1);
            Num=Integer.parseInt(num);
            JOptionPane.showMessageDialog(null,num);
            Num++; 
            }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not selected "+e);
               
                
        }
            try
            {
            stat=con.createStatement();
            stat.execute("insert into gk_questions values('"+Num+"','"+Question+"','"+OptionA+"','"+OptionB+"','"+OptionC+"','"+OptionD+"','"+Correct+"')");
            JOptionPane.showMessageDialog(null,"inserted");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Not inserted"+e);
            }
            }
            else if(Next.equals("RANDOM"))
            {
                {
                    try
        {
            PreparedStatement pr=con.prepareStatement("select * from random_questions");
            ResultSet rs=pr.executeQuery();
            rs.last();
            String num=rs.getString(1);
           Num=Integer.parseInt(num);
                     
            Num++;
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not selected"+e);
           
        }
            try
            {
                stat=con.createStatement();
                stat.execute("insert into random_questions values('"+Num+"','"+Question+"','"+OptionA+"','"+OptionB+"','"+OptionC+"','"+OptionD+"','"+Correct+"')");
            JOptionPane.showMessageDialog(null,"inserted");
            Num++;
            }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null,"not inserted"+e);
             }
                
            }
            }
                else if(Next.equals("CRICKET"))
            {
                {
                    try
        {
            PreparedStatement pr=con.prepareStatement("select * from cricket_questions");
            ResultSet rs=pr.executeQuery();
            rs.last();
            String num=rs.getString(1);
           Num=Integer.parseInt(num);
           Num++; 
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not selected"+Num+e);
     Num=1;
           
        }
            try{
                stat=con.createStatement();
                stat.execute("insert into cricket_questions values('"+Num+"','"+Question+"','"+OptionA+"','"+OptionB+"','"+OptionC+"','"+OptionD+"','"+Correct+"')");
            JOptionPane.showMessageDialog(null,"inserted");
            Num++;
            }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null,"not inserted"+Num+e);
                 
             }
                
            }
            
        }
            else if(Next.equals("SCIENCE"))
            {
                
                {
                    try
        {
            PreparedStatement pr=con.prepareStatement("select * from science_questions");
            ResultSet rs=pr.executeQuery();
            rs.last();
            String num=rs.getString(1);
            Num=Integer.parseInt(num);
            Num++;
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"not selected"+e);
            Num=1;
        }
            try{
                stat=con.createStatement();
                stat.execute("insert into science_questions values('"+Num+"','"+Question+"','"+OptionA+"','"+OptionB+"','"+OptionC+"','"+OptionD+"','"+Correct+"')");
            JOptionPane.showMessageDialog(null,"inserted");
            Num++;
            }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null,"not inseted"+e);
                
             }
            
                
            }
     
            }
        }
    }//GEN-LAST:event_uploadActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ADD obj=new ADD();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        question.setText("");
        optiona.setText("");
        optionb.setText("");
        optionc.setText("");
        optiond.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String Next="";
               
                new Questions(Next).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField optiona;
    private javax.swing.JTextField optionb;
    private javax.swing.JTextField optionc;
    private javax.swing.JTextField optiond;
    private javax.swing.JTextField question;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
